export const connectionText = {
  title: 'Connect to Desktop',
  subtitle: 'Make sure both devices are on the same Wi-Fi network.',
  qrTitle: 'Scan Desktop QR',
  scanQr: 'Scan QR Code',
  otherOptions: 'Other options',
  nearbyTitle: 'Nearby Desktops',
  connectionOptionsTitle: 'Connection Options',
  manualEntryTitle: 'Enter Address Manually',
  manualEntrySubtitle: 'Use this if QR scanning is unavailable.',
  manualServerAddressLabel: 'Server IP Address',
  manualIpPlaceholder: '192.168.1.x',
  manualFingerprintPlaceholder: 'SHA-256 fingerprint from Windows',
  manualTokenPlaceholder: 'Session token from Windows',
  connect: 'Connect',
  connecting: 'Connecting…',
  waitingApprovalTitle: 'Waiting for Windows approval',
  waitingApprovalMessage: (desktopName: string) =>
    `Approve this iPhone in Local Media Transfer on ${desktopName}. Keep this screen open.`,
  nearbyDisabledNative:
    'Nearby discovery is off. Enable it here and in Local Media Transfer Settings on Windows. QR and manual connection remain available.',
  nearbyDisabledExpo:
    'Nearby discovery needs the installed iOS app. Expo Go can still connect by QR code or manual HTTP address.',
  enableNearby: 'Enable Nearby Discovery',
  installedAppRequired: 'Installed App Required',
  searching: 'Searching…',
  refresh: 'Refresh',
  looking: 'Looking on your local network…',
  noDesktopFound: 'No desktop found. Try QR or manual entry.',
  discoveryRequiresInstalledApp: 'Automatic discovery requires the installed app. Use QR or manual connection.',
  tapToConnect: 'Tap to connect securely',
  useUnencryptedHttp: 'Use Unencrypted HTTP',
  explainUnencryptedHttp: 'Explain unencrypted HTTP',
  explainNearbyDiscovery: 'Explain nearby desktop discovery',
  httpNativeDetail: 'Only for older desktop builds. HTTPS stays preferred.',
  httpExpoDetail:
    'Expo Go uses HTTP and the compatibility uploader. Install the IPA for encrypted, faster native transfers.',
  unsupportedQrTitle: 'Unsupported QR code',
  unsupportedQrMessage: 'Scan the current pairing QR shown by the Windows application.',
  unsupportedPairingVersionTitle: 'Update iPhone app',
  unsupportedPairingVersionMessage: (version: number) =>
    `This Windows QR code uses pairing version ${version}. Install the latest iPhone app and scan again.`,
  connectionFailedTitle: 'Connection failed',
  connectionFailedMessage: 'The connection attempt failed. Check that Windows is running, then scan the QR code again.',
  cameraPermissionTitle: 'Permission Required',
  cameraPermissionMessage: 'Camera permission is required to scan QR codes.',
  cameraUnavailableTitle: 'Camera unavailable',
  cameraUnavailableMessage: 'The camera could not be opened. Try again or enter the desktop address manually.',
  discoveryFailed: 'Nearby discovery could not run. Check Wi-Fi access, then try again or scan the QR code.',
};
