// Generated by scripts/sync-transfer-limits.ps1. Do not edit.
enum TransferLimits {
  static let MaxChunksPerFile = 10000
  static let MaxFileBytes = 107374182400
  static let MaxQueuedFiles = 1000
  static let NativeChunkBytes = 8388608
  static let CompatibilityChunkBytes = 4194304
  static let WholeFileBytes = 104857600
  static let MaxChunkBytes = 67108864
  static let MaxEncodedChunkBytes = 94371840
}
