export const transferText = {
  title: 'Transfer Progress',
  preparingTitle: 'Preparing media',
  preparingSubtitle: 'Reading file information',
  duplicateCheckTitle: 'Checking possible duplicates',
  duplicateCheckSubtitle: 'Full SHA-256 · no upload bytes sent',
  filesLeft: 'Files left',
  currentSpeed: 'Speed',
  averageSpeed: 'Average speed',
  peakSpeed: 'Peak speed',
  estimate: 'Time left',
  summaryTitle: 'Transfer summary',
  uploaded: 'Uploaded',
  skipped: 'Skipped',
  failed: 'Failed',
  total: 'Total',
  selected: 'Selected',
  prepared: 'Prepared',
  transferred: 'Stored as new files',
  duration: 'Duration',
  recentActivity: 'Recent Activity',
  done: 'Done',
  cancelTransfer: 'Cancel Transfer',
  transferErrors: 'Transfer errors',
  allTransferResults: 'All transfer results',
  close: 'Close',
  virtualizedListLabel: (count: string) => `${count} results`,
  viewAllResults: (count: string) => `View all ${count}`,
  viewErrors: (count: string) => `View ${count} errors`,
  fatalErrorTitle: 'Upload Fatal Error',
  unknownError: 'Unknown error',
  unfinishedFileError: 'Upload failed before this file completed.',
};
