#pragma once
// Generated by scripts/sync-transfer-limits.ps1. Do not edit.
#include <cstdint>
namespace lmt::TransferLimits {
inline constexpr uint64_t MaxChunksPerFile = 10000ULL;
inline constexpr uint64_t MaxFileBytes = 107374182400ULL;
inline constexpr uint64_t MaxQueuedFiles = 1000ULL;
inline constexpr uint64_t NativeChunkBytes = 8388608ULL;
inline constexpr uint64_t CompatibilityChunkBytes = 4194304ULL;
inline constexpr uint64_t WholeFileBytes = 104857600ULL;
inline constexpr uint64_t MaxChunkBytes = 67108864ULL;
inline constexpr uint64_t MaxEncodedChunkBytes = 94371840ULL;
}
