// Generated by scripts/sync-transfer-limits.ps1. Do not edit.
namespace LocalMediaTransfer.WindowsClient;
public static class TransferLimits
{
    public const int MaxChunksPerFile = 10000;
    public const long MaxFileBytes = 107374182400;
    public const int MaxQueuedFiles = 1000;
    public const int NativeChunkBytes = 8388608;
    public const int CompatibilityChunkBytes = 4194304;
    public const int WholeFileBytes = 104857600;
    public const int MaxChunkBytes = 67108864;
    public const int MaxEncodedChunkBytes = 94371840;
}
