export const dashboardText = {
  title: 'Dashboard',
  loadingSettings: 'Loading settings…',
  chooseMedia: 'Choose Media',
  manage: 'Manage',
  copiedTitle: 'Copied',
  copiedAddressMessage: 'The server address was copied.',
  copyFailedTitle: 'Copy failed',
  copyFailedMessage: 'Could not copy the server address. Select and copy it manually.',
  linkFailedTitle: 'Could not open link',
  linkFailedMessage: 'The link could not be opened on this device.',
  desktopAddress: 'Desktop Address',
  desktopAddressSecret: 'Your approved-device credential stays hidden in the iOS Keychain and is never included here.',
  copyLink: 'Copy Address',
  localNetwork: 'Local network',
  tapSecurityDetails: 'Tap for secure connection details',
  encryptedStatus: (tlsVersion: string) => `Encrypted · ${tlsVersion} · certificate verified`,
  httpStatus: 'Using HTTP',
  reconnectingStatus: 'Connection interrupted · Retrying',
  disconnectedStatus: 'Desktop unavailable',
  retryConnection: 'Try reconnecting',
  httpWarning: 'Files and authentication credentials may be visible on this network.',
};
