[CmdletBinding()]
param([switch]$Check)
$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
$limits = Get-Content -Raw (Join-Path $root 'protocol/transfer-limits.json') | ConvertFrom-Json
$cpp = @('#pragma once', '// Generated by scripts/sync-transfer-limits.ps1. Do not edit.', '#include <cstdint>', 'namespace lmt::TransferLimits {')
$cs = @('// Generated by scripts/sync-transfer-limits.ps1. Do not edit.', 'namespace LocalMediaTransfer.WindowsClient;', 'public static class TransferLimits', '{')
$ts = @('// Generated by scripts/sync-transfer-limits.ps1. Do not edit.', 'export const TransferLimits = {')
$js = @('// Generated by scripts/sync-transfer-limits.ps1. Do not edit.', 'window.TransferLimits = Object.freeze({')
$swift = @('// Generated by scripts/sync-transfer-limits.ps1. Do not edit.', 'enum TransferLimits {')
foreach ($property in $limits.PSObject.Properties) {
    $name = $property.Name
    $value = [long]$property.Value
    if ($name -notmatch '^[A-Z][A-Za-z]+$' -or $value -le 0 -or $value -gt 9007199254740991) {
        throw 'Invalid transfer limit.'
    }
    $type = if ($value -le [int]::MaxValue) { 'int' } else { 'long' }
    $cpp += "inline constexpr uint64_t $name = ${value}ULL;"
    $cs += "    public const $type $name = $value;"
    $ts += "  ${name}: $value,"
    $js += "  ${name}: $value,"
    $swift += "  static let $name = $value"
}
$outputs = @{
    'src/Server/include/common/TransferLimits.hpp' = $cpp + '}'
    'src/LocalMediaTransfer.WindowsClient/TransferLimits.cs' = $cs + '}'
    'src/LocalMediaTransfer.iOS/src/services/upload/transferLimits.ts' = $ts + '} as const;'
    'src/LocalMediaTransfer.iOS/modules/local-media-transfer-native/ios/TransferLimits.swift' = $swift + '}'
    'src/Server/static/js/core/transfer-limits.js' = $js + '});'
}
foreach ($entry in $outputs.GetEnumerator()) {
    $path = Join-Path $root $entry.Key
    $expected = ($entry.Value -join "`n") + "`n"
    if ($Check) {
        if (!(Test-Path -LiteralPath $path) -or
            ([IO.File]::ReadAllText($path).Replace("`r`n", "`n") -cne $expected)) {
            throw "Transfer limits are stale: $($entry.Key). Run scripts/sync-transfer-limits.ps1."
        }
    } else {
        [IO.File]::WriteAllText($path, $expected, [Text.UTF8Encoding]::new($false))
    }
}
